name: Feature request
description: Propose an improvement
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior
    validations:
      required: true
  - type: textarea
    id: compatibility
    attributes:
      label: Ansible compatibility
      description: If relevant, describe ansible-inventory's behavior and version.
